GET http://127.0.0.1:8000/sanctum/csrf-cookie

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "collector@adopisoft.com",
    "password": "password"
}
###
GET http://127.0.0.1:8000/api/billers
Accept: application/json
Authorization: Bearer 5|b9auoUe9z9yI7ce9EGkGFQ9F0wM0nhr1hcjvGdjD

###
GET http://127.0.0.1:8000/api/billers/94288c07-72be-4af8-8437-e1b483c5460c
Accept: application/json

###
POST http://127.0.0.1:8000/api/billers
Accept: application/json
Content-Type: application/json

{
    "name": "MCWD",
    "type": "water"
}


###
GET http://127.0.0.1:8000/api/units
Accept: application/json

###
POST  http://127.0.0.1:8000/api/units
Accept: application/json
Content-Type: application/json

{
    "name": "Unit 1",
    "fund": 1000,
    "postal_code": "6000",
    "province": "Cebu",
    "city": "Cebu",
    "municipality": "Cebu",
    "barangay": "Talamban",
    "street": "Nasipit Rd."
}

###
PUT  http://127.0.0.1:8000/api/units/94288c07-6693-43e6-8d1e-54de62f72425
Accept: application/json
Content-Type: application/json

{
    "name": "Unit 2",
    "fund": 1000,
    "postal_code": "6000",
    "province": "Cebu",
    "city": "Cebu",
    "municipality": "Cebu",
    "barangay": "Talamban",
    "street": "Nasipit Rd."
}

###
GET http://127.0.0.1:8000/api/units/94288c07-6693-43e6-8d1e-54de62f72425
Accept: application/json

###
GET http://127.0.0.1:8000/api/units/94288c07-6693-43e6-8d1e-54de62f72425/transactions
Accept: application/json

###
GET http://127.0.0.1:8000/api/transactions
Accept: application/json

###
POST http://127.0.0.1:8000/api/units/945d1ed7-1edf-46b7-af09-800314887ae2/transactions
Accept: application/json
Content-Type: application/json

{
    "biller_id": "945d1ef5-f9c8-4afb-a8d1-5e8529e016b8",
    "service_number": "011156423214",
    "number": "09466640372",
    "amount": 10021,
    "status": "pending"
}

###
GET http://127.0.0.1:8000/api/remits?remittedBy=Gerald+Afable
Accept: application/json

###
POST http://127.0.0.1:8000/api/remits
Accept: application/json
Content-Type: application/json

{
    "remitted_by": "Gerald Afable",
    "total": 1000,
    "transaction_ids": [
        "943d2860-ff02-499c-aa7c-c4fdf45d5fe7",
        "943d2860-e42d-4e4a-8e10-19e9abfcda2b",
        "943d2860-d314-4ed8-8051-f8f5cb9079aa"
    ]
}

###
GET http://127.0.0.1:8000/api/remits/943d28ab-3700-416d-a16b-3a17ae011e37/transactions

Accept: application/json
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/collections
Accept: application/json
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/collections/945ea94d-5c30-4dae-b17a-24a9839f1506
Accept: application/json
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/collections
Accept: application/json
Content-Type: application/json

{
    "unit_id": "945d1ef6-3941-486e-9ecc-8e69e97a04b8",
    "collected_by": "John Doe",
    "total": 10000,
    "collected_at": "2021-08-05"
}

###
PUT http://127.0.0.1:8000/api/collections/945ea94d-5c30-4dae-b17a-24a9839f1506
Accept: application/json
Content-Type: application/json

{
    "unit_id": "945aeed8-01aa-41b9-b319-37e9c7b4e6bf",
    "collected_by": "Gerald Afable Update",
    "total": 10000,
    "collected_at": "2021-08-05"
}

###
GET http://127.0.0.1:8000/api/billers/945d1ef5-f9c8-4afb-a8d1-5e8529e016b8/accounts
Accept: application/json

###
GET http://127.0.0.1:8000/api/dashboard
Accept: application/json

###
GET http://127.0.0.1:8000/api/dashboard/transactions/preview
Accept: application/json

###
GET http://127.0.0.1:8000/api/users
Accept: application/json

###
GET http://127.0.0.1:8000/api/users/94736870-69dc-4d56-b13f-1e4851912073
Accept: application/json

###
POST http://127.0.0.1:8000/api/users
Accept: application/json
Content-Type: application/json

{
    "name": "Admin 2",
    "email": "collector1@adopisoft.com",
    "password": "password",
    "roles": ["Admin","Manager"]
}

###
PUT http://127.0.0.1:8000/api/users/94737123-a777-4e71-8699-54da8b94bfe8
Accept: application/json
Content-Type: application/json

{
    "name": "Collector",
    "email": "collector@adopisoft.com",
    "password": "password"
}

###
GET http://127.0.0.1:8000/api/users/94736870-69dc-4d56-b13f-1e4851912073/roles/hasAccess
Accept: application/json
Content-Type: application/json

{
    "roles": ["Manager"]
}

###

GET http://127.0.0.1:8000/api/feedback
Accept: application/json
Authorization: Bearer 26|Y0ixMdKTVTGx2S2Ewj5YJIBvMUneTWQpTsT8KXj1

